/*!

\file UiViews.hpp
\brief Enter your brief here //TODO
\author Eben
\version 0.1

*/

#ifndef SPORZOBC_WAL_UIVIEWS_HPP
#define SPORZOBC_WAL_UIVIEWS_HPP

enum UiViews {
    NO_VIEW,
    MAIN_MENU,
    PLAYER_SELECT,
    ELECT_CHIEF,
    GAME_INFORMATION,
    DISCUSS,
    ELIMINATION,
    EVENING_BED_TIME,
    MORNING_WAKING_UP,
    VOTING_PHASE_END,
    VOTING_PHASE_RESULT,
    VOTING_PHASE_TARGET,
    COMPUTER_SCIENTIST_RESULT,
    COMPUTER_SCIENTIST_TURN,
    DOCTORS_KILL_OR_HEAL_CHOICE,
    DOCTORS_KILL_OR_HEAL_TARGET,
    DOCTORS_RECAP,
    DOCTORS_TURN,
    GENETICIST_RESULT,
    GENETICIST_TARGET,
    GENETICIST_TURN,
    HACKER_RESULT,
    HACKER_TARGET,
    HACKER_TURN,
    MUTANTS_KILL_OR_MUTATE_CHOICE,
    MUTANTS_KILL_OR_MUTATE_TARGET,
    MUTANT_PARALYSIS_TARGET,
    MUTANTS_RECAP,
    MUTANTS_TURN,
    NOVICE_HACKER_RESULT,
    NOVICE_HACKER_TARGET,
    NOVICE_HACKER_TURN,
    PAINTER_RESULT,
    PAINTER_TARGET,
    PAINTER_TURN,
    PSYCHOLOGIST_RESULT,
    PSYCHOLOGIST_TARGET,
    PSYCHOLOGIST_TURN,
    SPY_RESULT,
    SPY_TARGET,
    SPY_TURN
};

#endif //SPORZOBC_WAL_UIVIEWS_HPP
